version: '3.7'

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    hostname: 'rabbitmq'
    environment:
      RABBITMQ_ERLANG_COOKIE: 'SWQOKODSQALRPCLNMEQG'
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
      RABBITMQ_DEFAULT_VHOST: '/'
    ports:
      - '15673:15672'
      - '5673:5672'
    labels:
      NAME: 'rabbitmq'
    networks:
      - backend