version: '3.7'

services:

  simplic_ox:
    image: 'simplic.azurecr.io/simplic-ox:latest'
    container_name: simplic_ox
    hostname: 'simplic_ox'
    ports:
      - '8081:80'
    labels:
      NAME: 'simplic_ox'
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend
      - frontend

  signoz:
    image: signoz/frontend:0.8.0
    container_name: signoz
    hostname: signoz
    restart: on-failure
    depends_on:
      - alertmanager
      - query-service
    ports:
      - "3301:3301"
    volumes:
      - ./config/nginx-config.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
      - frontend

