version: '3.7'

services:
  simplic_mail:
    image: '${simplic_mail_image}'
    container_name: simplic_mail
    hostname: 'simplic_mail'
    ports:
      - '8086:80'
    labels:
      NAME: 'simplic_mail'
    depends_on:
       - mongodb
       - rabbitmq
       - otel-collector
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - Mailing__SendInBlueKey=${api_key_send_in_blue}
    networks:
      - backend
      - frontend

  simplic_auth:
    image: '${simplic_auth_image}'
    container_name: simplic_auth
    hostname: 'simplic_auth'
    ports:
      - '8084:80'
    labels:
      NAME: 'simplic_auth'
    depends_on:
       - mongodb
       - rabbitmq
       - otel-collector
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - InternalHosts__organization=${internal_hosts_organization}
    networks:
      - backend
      - frontend

  simplic_member:
    image: '${simplic_member_image}'
    container_name: simplic_member
    hostname: 'simplic_member'
    ports:
      - '8085:80'
    labels:
      NAME: 'simplic_member'
    depends_on:
       - mongodb
       - rabbitmq
       - otel-collector
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend
      - frontend

  simplic_organization:
    image: '${simplic_organization_image}'
    container_name: simplic_organization
    hostname: 'simplic_organization'
    ports:
      - '8087:80'
    labels:
      NAME: 'simplic_organization'
    depends_on:
       - mongodb
       - rabbitmq
       - otel-collector
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - InternalHosts__auth=${internal_hosts_auth}
    networks:
      - backend
      - frontend

  simplic_oxbase:
    image: '${simplic_oxbase_image}'
    container_name: simplic_oxbase
    hostname: 'simplic_oxbase'
    ports:
      - '8088:80'
    labels:
      NAME: 'simplic_oxbase'
    depends_on:
       - mongodb
       - rabbitmq
       - otel-collector
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend
      - frontend

  simplic_erp:
    image: '${simplic_erp_image}'
    container_name: simplic_erp
    hostname: 'simplic_erp'
    ports:
      - '8089:80'
    labels:
      NAME: 'simplic_erp'
    depends_on:
       - mongodb
       - rabbitmq
       - otel-collector
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend
      - frontend

  simplic_timeslot:
    image: '${simplic_timeslot_image}'
    container_name: simplic_timeslot
    hostname: 'simplic_timeslot'
    ports:
      - '8090:80'
    labels:
      NAME: 'simplic_timeslot'
    depends_on:
       - mongodb
       - rabbitmq
       - otel-collector
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - InternalHosts__auth=${internal_hosts_auth}
       - InternalHosts__organization=${internal_hosts_organization}
    networks:
      - backend
      - frontend

  simplic_contact:
    image: '${simplic_contact_image}'
    container_name: simplic_contact
    hostname: 'simplic_contact'
    ports:
      - '8091:80'
    labels:
      NAME: 'simplic_contact'
    depends_on:
       - mongodb
       - rabbitmq
       - otel-collector
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - InternalHosts__auth=${internal_hosts_auth}
       - InternalHosts__organization=${internal_hosts_organization}
    networks:
      - backend
      - frontend

  simplic_contract:
      image: '${simplic_contract_image}'
      container_name: simplic_contract
      hostname: 'simplic_contract'
      ports:
        - '8092:80'
      labels:
        NAME: 'simplic_contract'
      depends_on:
        - mongodb
        - rabbitmq
        - otel-collector
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - InternalHosts__auth=${internal_hosts_auth}
        - InternalHosts__organization=${internal_hosts_organization}
      networks:
        - backend
        - frontend

  simplic_construction_site:
      image: '${simplic_construction_site_image}'
      container_name: simplic_construction_site
      hostname: 'simplic_construction_site'
      ports:
        - '8093:80'
      labels:
        NAME: 'simplic_construction_site'
      depends_on:
        - mongodb
        - rabbitmq
        - otel-collector
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - InternalHosts__auth=${internal_hosts_auth}
        - InternalHosts__organization=${internal_hosts_organization}
      networks:
        - backend
        - frontend

  simplic_taskboard:
      image: '${simplic_taskboard_image}'
      container_name: simplic_taskboard
      hostname: 'simplic_taskboard'
      ports:
        - '8094:80'
      labels:
        NAME: 'simplic_taskboard'
      depends_on:
        - mongodb
        - rabbitmq
        - otel-collector
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - InternalHosts__auth=${internal_hosts_auth}
        - InternalHosts__organization=${internal_hosts_organization}
      networks:
        - backend
        - frontend
        
  simplic_logistics:
    image: '${simplic_logistics_image}'
    container_name: simplic_logistics
    hostname: 'simplic_logistics'
    ports:
      - '8095:80'
    labels:
      NAME: 'simplic_logistics'
    depends_on:
       - mongodb
       - rabbitmq
       - otel-collector
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend
      - frontend

  
  simplic_datahub:
    image: '${simplic_datahub_image}'
    container_name: simplic_datahub
    hostname: 'simplic_datahub'
    ports:
      - '8096:80'
    labels:
      NAME: 'simplic_datahub'
    depends_on:
       - mongodb
       - rabbitmq
       - otel-collector
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend
      - frontend

  simplic_article:
    image: '${simplic_article_image}'
    container_name: simplic_article
    hostname: 'simplic_article'
    ports:
      - '8097:80'
    labels:
      NAME: 'simplic_article'
    depends_on:
       - mongodb
       - rabbitmq
       - otel-collector
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend
      - frontend

  simplic_resource_locking:
    image: '${simplic_resource_locking_image}'
    container_name: simplic_resource_locking
    hostname: 'simplic_resource_locking'
    ports:
      - '8098:80'
    labels:
      NAME: 'simplic_resource_locking'
    depends_on:
       - mongodb
       - rabbitmq
       - otel-collector
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend
      - frontend