version: '3.7'

services:
  simplic_mail:
    image: '${simplic_mail_image}'
    container_name: simplic_mail
    hostname: 'simplic_mail'
    ports:
      - '8086:80'
    labels:
      NAME: 'simplic_mail'
    depends_on:
       - mongodb
       - rabbitmq
       - otel-collector
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - Mailing__SendInBlueKey=${api_key_send_in_blue}
    networks:
      - backend
      - frontend

  simplic_auth:
    image: '${simplic_auth_image}'
    container_name: simplic_auth
    hostname: 'simplic_auth'
    ports:
      - '8084:80'
    labels:
      NAME: 'simplic_auth'
    depends_on:
       - mongodb
       - rabbitmq
       - otel-collector
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - InternalHosts__organization=${internal_hosts_organization}
    networks:
      - backend
      - frontend

  simplic_member:
    image: '${simplic_member_image}'
    container_name: simplic_member
    hostname: 'simplic_member'
    ports:
      - '8085:80'
    labels:
      NAME: 'simplic_member'
    depends_on:
       - mongodb
       - rabbitmq
       - otel-collector
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend
      - frontend

  simplic_organization:
    image: '${simplic_organization_image}'
    container_name: simplic_organization
    hostname: 'simplic_organization'
    ports:
      - '8087:80'
    labels:
      NAME: 'simplic_organization'
    depends_on:
       - mongodb
       - rabbitmq
       - otel-collector
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - InternalHosts__auth=${internal_hosts_auth}
    networks:
      - backend
      - frontend

  simplic_oxbase:
    image: '${simplic_oxbase_image}'
    container_name: simplic_oxbase
    hostname: 'simplic_oxbase'
    ports:
      - '8088:80'
    labels:
      NAME: 'simplic_oxbase'
    depends_on:
       - mongodb
       - rabbitmq
       - otel-collector
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend
      - frontend

